driver/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'driver'

urlpatterns = [
    url(r'^search/', views.search_location, name='Search'),
    url(r'^edit-profile/', views.edit_profile, name='edit_profile'),
    url(r'^profile/(\d+)', views.update_profile, name='profile'),
    url(r'^car-details/', views.car_details, name='car_details'),
    url(r'^$', views.home, name='home'),
    url(r'^home/$', views.homed, name='homed'),
    url(r'^pay/$', views.trigger_payment, name='trigger_payment'),
    url(r'^status-success/$', views.status_success, name='status_success'),
    url(r'^status-failed/$', views.status_failed, name='status_failed'),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

egeshaProject/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from . import views as project_views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', project_views.landing, name='landing'),
    url(r'^lot/', include('lotOwner.urls')),
    url(r'^operator/', include('lotManager.urls')),
    url(r'^user/', include('accounts.urls')),
    url(r'^driver/', include('driver.urls')),
    # url(r'^egeshapay/', include('egeshapay.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lotOwner/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'lotOwner'

urlpatterns=[
    url(r'^owner/',views.home, name='Lot'),
    url(r'^details/(\d+)',views.Lotdetail,name='Details'),
    url(r'^map/(\d+)',views.map,name='Map'),
    url(r'^location/(\d+)',views.location,name='Location'),
    url(r'^edit/(\d+)',views.edit_profile,name='Edit'),
    url(r'^edit_lot/(\d+)',views.edit_lot,name='Edit_Lot'),
    url(r'^payment/(\d+)',views.payment,name="Payment"),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lotOwner/models.py
from django.db import models
from accounts.models import OwnerProfile


class LotDetails(models.Model):
    '''
    We create a lot details model to store information about the lot details
    '''
    Name_of_lot=models.CharField(max_length=40)
    Image_of_Lot=models.ImageField(upload_to='images/',null=True)
    Total_number_of_spaces=models.IntegerField()
    owner=models.ForeignKey(OwnerProfile, null=True)

    def __str__(self):
        return self.Name_of_lot
class Location(models.Model):
    '''
    We create a location model to store information about the location of the lot
    '''
    '''
    we add a lotdetails  foreignkey to filter the location depending on the lot
    '''
    name_of_location = models.CharField(max_length=40)
    latitude = models.DecimalField(max_digits=9, decimal_places=6, null=True, blank=True)
    longitude = models.DecimalField(max_digits=9, decimal_places=6, null=True, blank=True)
    lot=models.ForeignKey(LotDetails,null=True,related_name='locations',related_query_name='location')
    def __str__(self):
        return self.name_of_location
    @classmethod
    def search (cls,search_term):
        locations=cls.objects.filter(name_of_location__icontains=search_term)
        return locations
class PaymentDetails(models.Model):
    Bank_name=models.CharField(max_length=40)
    Account_number=models.CharField(max_length=40)
    owner=models.ForeignKey(OwnerProfile,null=True)

lotOwner/forms.py
from django import forms
from .models import LotDetails, Location,PaymentDetails
from accounts.models import OwnerProfile


class OwnerProfileForm(forms.ModelForm):
    '''
    We create an owner profile form to save the owner's information
    '''
    class Meta:
        model=OwnerProfile
        fields=('avatar','bio','national_id','phone_number')


class LotDetailsForm(forms.ModelForm):
    '''
    we create a lot details form to pick information about the lot
    '''
    class Meta:
        model=LotDetails
        fields=('Name_of_lot','Image_of_Lot','Total_number_of_spaces')
class PaymentForm(forms.ModelForm):
    '''
    we create a form to pick up lot owner's account details
    '''
    class Meta:
        model=PaymentDetails
        fields=('Bank_name','Account_number')

lotOwner/views.py
from django.shortcuts import render, redirect
from accounts.models import OwnerProfile
from .models import LotDetails,Location
from .forms import LotDetailsForm,OwnerProfileForm,PaymentForm
from django.contrib.auth.models import User
import googlemaps
#we import the serializers to convert the data from python to json
from django.core import serializers
from django.core.serializers import serialize
import json
from django.core.serializers.json import DjangoJSONEncoder
# Create your views here.

def home(request):
    current_user=request.user.id
    # title='Welcome lot owner'
    lots=''
    current_profile=''

    current_user_name=OwnerProfile.objects.filter(id=request.user.id)
    current_profile=OwnerProfile.objects.filter(user=current_user)
    location=''
    if current_user_name.exists():
        current_profile=OwnerProfile.objects.filter(user=current_user)
        lots=LotDetails.objects.filter(owner=current_profile)
        location=Location.objects.all()

    else:
        print('no profile')

    if request.method == 'POST':
        form1=OwnerProfileForm(request.POST, request.FILES)
        if form1.is_valid():
            user_profile=form1.save(commit=False)
            user_profile.user=request.user
            user_profile.save( )
            return redirect('/lot/owner/')
    else:
        form1=OwnerProfileForm()
    spots=list(Location.objects.all())


    print(spots)
    coords={"1":1,"2":2}
    coords_json=json.dumps(coords,cls=DjangoJSONEncoder)
    spots_json=serializers.serialize('json',spots,cls=DjangoJSONEncoder)

    return render (request,'Lot/home.html',{"lots":lots,"current_profile":current_profile,"form1":form1,"location":location,"coords_json":coords_json,"spots_json":spots_json})


def Lotdetail(request,profile_id):
    current_profile=''
    current_user=request.user
    current_profile=OwnerProfile.objects.get(id=profile_id)



    if request.method == 'POST':
        form = LotDetailsForm(request.POST,request.FILES)
        if form.is_valid():
            details = form.save(commit=False)
            details.owner = current_profile
            details.save()

            return redirect('/lot/owner/')

    else:
        form=LotDetailsForm()

    return render(request,'Lot/details.html',{"form":form,"current_profile":current_profile,"current_user":current_user})


def map(request,lot_id):

    lot_owner=OwnerProfile.objects.get(id=request.user.id)
    lot=LotDetails.objects.get(id=lot_id)
    gmaps=googlemaps.Client(key='AIzaSyBmrKc7FjQwLm9vEtseo5LK7Z6M_1aPm5k')
    title='hello'
    results=gmaps.geocode('nairobi')

    print('I am here 1')

    if 'address' in request.GET and request.GET['address']:
        address1=request.GET.get("address")
        geo=gmaps.geocode(address1)
        print('I am here')

        latitude=geo[0]['geometry']['location'].get('lat')
        longitude=geo[0]['geometry']['location'].get('lng')
        location=Location()
        print(latitude)
        print(longitude)
        location.name_of_location=address1
        location.latitude=latitude
        location.longitude=longitude
        location.lot=lot
        location.save()
        return redirect ('/lot/owner/')

    else:
        print('Not working')
    return redirect('/lot/owner/')


def location(request,lot_id):
    current_user=request.user.id
    lot=LotDetails.objects.get(id=lot_id)

    spots=''
    current_user_name=OwnerProfile.objects.filter(id=request.user.id)

    if current_user_name.exists():
        current_profile=OwnerProfile.objects.get(id=current_user)
        lots=LotDetails.objects.all()
        spots=list(Location.objects.filter(lot=lot))

        print(spots)
    coords={"1":1,"2":2}
    coords_json=json.dumps(coords,cls=DjangoJSONEncoder)
    spots_json=serializers.serialize('json',spots,cls=DjangoJSONEncoder)
    return render (request,'Lot/location.html',{"coords_json":coords_json,"spots_json":spots_json,"lot":lot})
def edit_profile(request,profile_id):
    current_profile=OwnerProfile.objects.get(id=profile_id)
    if request.method == 'POST':
        form=OwnerProfileForm(request.POST, request.FILES,instance=current_profile)
        if form.is_valid():
            user_profile=form.save(commit=False)
            user_profile.user=request.user
            user_profile.save( )
            return redirect('/lot/owner/')
    else:
        form=OwnerProfileForm()
    return render (request,'Lot/edit_profile.html',{"form":form,"current_profile":current_profile})
def edit_lot(request,lot_id):
    lot=LotDetails.objects.get(id=lot_id)
    if request.method == 'POST':
        form = LotDetailsForm(request.POST,request.FILES,instance=lot)
        if form.is_valid():
            details = form.save(commit=False)
            details.save()

            return redirect('/lot/owner/')

    else:
        form=LotDetailsForm()
    return render (request,'Lot/edit_lot.html',{"form":form,"lot":lot})
def payment(request,profile_id):
    current_profile=OwnerProfile.objects.get(id=profile_id)
    if request.method == 'POST':
        form=PaymentForm(request.POST, request.FILES)
        if form.is_valid():
            user_profile=form.save(commit=False)
            user_profile.owner=current_profile
            user_profile.save()
            return redirect('/lot/owner/')
    else:
        form=PaymentForm()
    return render(request,'Lot/payment.html',{"form":form,"current_profile":current_profile})

lotOwner/templates/Lot/details.html
{%extends 'Lot/base.html'%} {% load bootstrap3 %} {% load static %} {% block content %}
<div class="container-fluid" style="padding-top: 8%; background-color:#D5DFD5;">
  <div class="row" style="">
    <h1 class="text-center"><strong>Lot Details</strong></h1>
    <div class="col-md-3"></div>
    <div class="col-md-6 ">
      <div class="well">
        {{form.media}}
        <form action="{% url 'lotOwner:Details' current_user.id %}" method="post" enctype="multipart/form-data">
          {%csrf_token%} {% bootstrap_form form%}
          <input type="submit" class="btn btn-info btn-lg" value="Save">
        </form>
      </div>


    </div>
    <div class="col-md-3"></div>
  </div>

  <br><br><br><br><br><br><br><br>
</div>

{%endblock%}

lotOwner/templates/Lot/edit_lot.html
 {%extends 'Lot/base.html'%} {% load bootstrap3 %} {% load static %} {% block content %}
<div class="container-fluid" style="padding-top: 8%; background-color:#D5DFD5;">
  <div class="row" style="">
    <h1 class="text-center"><strong>Lot Details</strong></h1>
    <div class="col-md-3"></div>
    <div class="col-md-6 ">
      <div class="well">
        {{form.media}}
        <form action="{% url 'lotOwner:Edit_Lot' lot.id %}" method="post" enctype="multipart/form-data">
          {%csrf_token%} {% bootstrap_form form%}
          <input type="submit" class="btn btn-info btn-lg" value="Save">
        </form>
      </div>


    </div>
    <div class="col-md-3"></div>
  </div>

  <br><br><br><br><br><br><br><br>
</div>

{%endblock%}

lotOwner/templates/Lot/edit_profile.html
{%extends 'Lot/base.html'%} {% load bootstrap3 %} {% load static %} {% block content %}
<br><br><br><br><br><br><br>
<div class="container">
  <form action="{% url 'lotOwner:Edit' current_profile.id %}" method="post" enctype="multipart/form-data">
    {%csrf_token%} {% bootstrap_form form %}
    <input type="submit" class="btn btn-warning btn-lg" value="Save Changes">
  </form>
</div>
{% endblock %}

lotOwner/templates/Lot/home.html
{%extends 'Lot/base.html'%} {% load bootstrap3 %} {% load static %}
<!--  -->
{% block content %}


<br><br><br><br> {% for current in current_profile %}
<div class="container">
  <h1 class="text-center" style="font-family: 'Raleway', sans-serif;">Lot Owner</h1>
</div>
<div class="container">
  <img src="{{current.avatar.url}}" class="img-responsive" style="height:35%;width:45%;" alt="Image">
  <h2 style="font-family: 'Raleway', sans-serif">Name: {{current.user.username}}</h2>
  <h2 style="font-family: 'Raleway', sans-serif">Phone_Number: {{current.phone_number}}</h2>
  <h2 style="font-family: 'Raleway', sans-serif">National_id: {{current.national_id}}</h2>
</div>


<br><br><br>
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-5 col-md-4 sidebar well" style="background:white;">
      {% if user %}
      <div class="">
        <!-- Heading -->
        <h2 class="text-center mb-4">
                          {{ user.username|title }}
                      </h2>
      </div>{% endif %} {%if current_profile%} {% for current in current_profile %}
      <div class="well">
        <div class="container">
          <h1 class="text-center" style="font-family: 'Raleway', sans-serif;">Lot Owner</h1>
        </div>
        <div class="container">
          <img src="{{current.avatar.url}}" class="img-responsive img-fluid img-rounded" style="height:250px;width:320px;" alt="Image">
          <h4 style="font-family: 'Raleway', sans-serif">Name: {{current.user.username}}</h4>
          <h4 style="font-family: 'Raleway', sans-serif">Phone : {{current.phone_number}}</h4>
          <h4 style="font-family: 'Raleway', sans-serif">National ID: {{current.national_id}}</h4>
        </div>
      </div>
      {% endfor %} {%endif%}

      <div class="well">
        <div class="container">
          {% for lot in lots %}
          <!-- <div class="col-md-4 col-sm-6 col-xs-12"> -->


          <a href="{% url 'lotOwner:Location' lot.id %}"><img src="{{lot.Image_of_Lot.url}}" class="img-responsive img-fluid img-rounded" style="height:250px;width:320px;" alt="Image"></a>

          <h2 style="font-family: 'Raleway', sans-serif">Lot Name: {{lot.Name_of_lot|title}}</h2>
          <p style="font-family: 'Raleway', sans-serif">Total spaces: {{lot.Total_number_of_spaces}}</p>

          <p style="font-family: 'Raleway', sans-serif">Located at: {{location.name_of_location}}</p>
          <button type="button" class="btn btn-info"><a href="{% url 'lotOwner:Edit_Lot' lot.id %}" style="color:white;">Edit Lot details</a></button>

          <!-- </div> -->
          {% empty %}

          <h3 style="font-family: 'Raleway', sans-serif">No Lot information Available</h3>
          <!--  -->
          {%if current_profile%}
          <a href="{% url 'lotOwner:Details' request.user.id %}" style="font-family: 'Raleway', sans-serif">
            <h3>Add Lot details</h3></a>
          <!--  -->
          {%else%}

          <!-- <h3 style="font-family: 'Raleway', sans-serif">Create Profile</h3> -->
          <!--  -->
          {%endif%}
          <!--  -->
          {% endfor %}

        </div>
      </div>
    </div>
  </div>
  <div class="col-sm-7 col-sm-offset-5 col-md-8 col-md-offset-4 main" style="background-color:#D5DFD5;">
    <br><br> {%if current_profile%}
    <div class="container-fluid">
      <h1 class="page-header"> Lot Map </h1>
      <!-- <h2 class="text-muted">free!</h2> -->

    </div>
    <br>
    <div class="container-fluid text-center">

      <div id="map_1" class="well"></div>

    </div>
    {% else %}
    <div class="container-fluid">
      <h1 class="page-header" style="font-family: 'Raleway', sans-serif;">Create Profile</h1>
    </div>
    <br><br>
    <div class="container well" style="width:650px">
      <form action="{% url 'lotOwner:Lot' %}" method="post" enctype="multipart/form-data">
        {%csrf_token%} {% bootstrap_form form1 %}

        <input type="submit" class="btn btn-warning btn-lg" value="Create profile">
      </form>

    </div>
    {%endif%}
    <br><br><br>
  </div>

  <hr>

</div>
{% endfor %} {% endblock %}
<!--  -->
{% block scripts %}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
{% bootstrap_javascript %}
<script>
    // we declare the following as global variables
    var map;
    var marker;
    var infowindow;
    var messagewindow;
    var marker1;
    var $lat;
    var $lon;

    function initMap() {
        //location of Nairobi is stored in a varibale
        var myLatLng = {
            lat: -1.28333,
            lng: 36.81667
        };
        var mombasa = {
            lat: -1.3007,
            lng: 36.7849
        };
        map = new google.maps.Map(document.getElementById('map_1'), {
            center: myLatLng,
            zoom: 13
        });
        // the marker is positioned at Nairobi
        //the infowindow retrives the form element when clicking a marker
        marker1 = new google.maps.Marker({
            position: myLatLng,
            map: map,
        })



        //we assign a click listener  with the addListener that creates a marker when the user clicks the map





        // we create a variable called spots that store the spots that we passed from the view function
        var spots = JSON.parse('{{spots_json|safe}}');
        console.log(spots);
        for (var i = 0; i < spots.length; i++) {
            console.log('yess its working');
            //we store the lat and long in the variables
            var lat = parseFloat(spots[i].fields.latitude)
            var lng = parseFloat(spots[i].fields.longitude)
            var name = spots[i].fields.name_of_location
                //Assign them positions lat being index 0
            coords = [lat, lng]
                //we log them to the console to check if the function is working
                //console.log(coords);
            console.log(name)
            var LatLng = new google.maps.LatLng(coords[0], coords[1]);
            var marker = new google.maps.Marker({
                position: LatLng,
                map: map
            });

        }


    }
</script>
  <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBmrKc7FjQwLm9vEtseo5LK7Z6M_1aPm5k&callback=initMap"></script>


  <script src="//cdnjs.cloudflare.com/ajax/libs/jquery.matchHeight/0.7.0/jquery.matchHeight-min.js"></script>

  {% endblock %}

lotOwner/templates/Lot/location.html
{%extends 'Lot/base.html'%}{% load bootstrap3 %} {% load static %}
<!--  -->
{% block content %}

<h3 class="page-header text-center">Set Lot Location</h3>


</div>
<div class="container">
  <div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-10">
      <div id="form">
        <form class="navbar-form" role="search" action="{% url 'lotOwner:Map' lot.id %}">

          <div class="input-group">
            <input type="text" class="form-control" placeholder="Enter Lot location " name="address">
            <div class="input-group-btn">
              <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
            </div>
          </div>

        </form>
        <div id="map" class="well"></div>
      </div>
      <div class="col-md-1"> </div>

    </div>

  </div>


  <br><br><br> {%endblock%}
  <!--  -->
  {% block scripts %}

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  {% bootstrap_javascript %}
  <script>
    // we declare the following as global variables
    var map;
    var marker;
    var infowindow;
    var messagewindow;
    var marker1;
    var $lat;
    var $lon;

    function initMap() {
      //location of Nairobi is stored in a varibale
      var myLatLng = {
        lat: -1.28333,
        lng: 36.81667
      };
      var mombasa = {
        lat: -1.3007,
        lng: 36.7849
      };
      map = new google.maps.Map(document.getElementById('map'), {
        center: myLatLng,
        zoom: 13
      });
      // the marker is positioned at Nairobi
      //the infowindow retrives the form element when clicking a marker
      marker1 = new google.maps.Marker({
        position: myLatLng,
        map: map,
      })


      infowindow = new google.maps.InfoWindow({
        content: document.getElementById('form')
      });
      // retrives the message element on saving the info window
      messagewindow = new google.maps.InfoWindow({
        content: document.getElementById('message')

      });
      //we assign a click listener  with the addListener that creates a marker when the user clicks the map
      google.maps.event.addListener(map, 'click', function(event) {

        marker = new google.maps.Marker({
          position: event.latLng,
          map: map
        });
        google.maps.event.addListener(marker, 'click', function() {
          infowindow.open(map, marker);

        });

      });


      // we create a variable called spots that store the spots that we passed from the view function
      var spots = JSON.parse('{{spots_json|safe}}');
      console.log(spots);
      for (var i = 0; i < spots.length; i++) {
        console.log('yess its working');
        //we store the lat and long in the variables
        var lat = parseFloat(spots[i].fields.latitude)
        var lng = parseFloat(spots[i].fields.longitude)
        var name = spots[i].fields.name_of_location
        //Assign them positions lat being index 0
        coords = [lat, lng]
        //we log them to the console to check if the function is working
        //console.log(coords);
        console.log(name)
        var LatLng = new google.maps.LatLng(coords[0], coords[1]);
        var marker = new google.maps.Marker({
          position: LatLng,
          map: map
        });

      }

    }
  </script>
  <!--we load the api from the specified api, the async attribute allows the page to
    load as the api loads the call back paramater executes the initMap() function that specifies the latitude and longitude of where the map will
    be centered
  -->
  <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBmrKc7FjQwLm9vEtseo5LK7Z6M_1aPm5k&callback=initMap"></script>

  <script src="//cdnjs.cloudflare.com/ajax/libs/jquery.matchHeight/0.7.0/jquery.matchHeight-min.js"></script>

  {% endblock %}

lotOwner/templates/Lot/navbar.html
{% load bootstrap3 %}
<!--  -->
{% load static%}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<body data-spy="scroll" data-target=".navbar" data-offset="50">

  <nav class="navbar navbar-default navbar-fixed-top justify-content-between" style="height:75px; padding-top:10px; margin-bottom:0">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="/" style="padding-top:0px;">
                    <img class="img-responsive img-fluid" src="{% static '/images/logo.png' %}" width="65px" height="65px" alt="icon"><span></span>
                </a>
        <a class="navbar-brand" href="/lot/owner/" style="font-family: 'Lobster', cursive; font-weight: 700;font-size: 2.5em;"><strong>Egesha</strong></a>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          {% if current_profile %}


          <!-- <li class=""><a href="{% url 'lotOwner:Details' request.user.id %}" style="font-family: 'Raleway', sans-serif;font-size:25px;color:black;font-size: 1.2em;">Add Lot Details<span class="sr-only">(current)</span></a></li> -->

          {% else %} {% endif %}
        </ul>
        <ul class="nav navbar-nav navbar-right pull-right">
          <li>
            <a href="/user/logout" style="font-family: 'Raleway', sans-serif; color:black;font-size: 1.2em;">Logout</a>
          </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">

          <li class="dropdown">
            <a href="#" style="font-family: 'Raleway', sans-serif; color:black;font-size: 1.2em;" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><strong>{{user.username|title}} </strong><span class="caret"></span></a>
            <ul class="dropdown-menu">

              <li class="text-center text-muted" style="font-family: 'Montserrat', sans-serif; color:black;font-size: 1.2em;"><strong>@ {{user.username}}</strong></li>
              <li role="separator" class="divider"></li>

              <li><a href="{% url 'lotOwner:Edit' request.user.id %}" style="font-family: 'Raleway', sans-serif; color:black;font-size: 1.2em;">Edit Profile</a></li>

              {% if current_profile %}

              <li class=""><a href="{% url 'lotOwner:Details' request.user.id %}" style="font-family: 'Raleway', sans-serif;font-size:25px;color:black;font-size: 1.2em;">Edit Lot Details<span class="sr-only">(current)</span></a></li>
              <li class=""><a href="{%url 'lotOwner:Payment' request.user.id %}" style="font-family: 'Raleway', sans-serif;font-size:25px;color:black;font-size: 1.2em;">Edit Payment details <span class="sr-only">(current)</span></a></li>

              {% else %}
              <!--  -->
              {% endif %}

            </ul>






      </div>
    </div>

  </nav>
</body>

</html>

lotOwner/templates/Lot/navbar1.html
<!DOCTYPE html>
<html lang="en">
<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
<link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
<nav class="navbar navbar-default" >
  <div class="container-fluid">
    <div class="navbar-header">
     <a class="navbar-brand" href="#" style="font-family: 'Raleway', sans-serif; font-size:35px;color:black;">Egesha</a>
   </div>
   <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="{% url 'Details' request.user.id %}"  style="font-family: 'Raleway', sans-serif;font-size:25px;color:black;">Add Lot Details<span class="sr-only">(current)</span></a></li>
        <li class=""><a href="#" style="font-family: 'Raleway', sans-serif;font-size:25px;color:black;"> <span class="sr-only"></span>Edit Profile</a></li>

      </ul>




  </div>
</div>

</nav>
</body>
</html>

lotOwner/templates/Lot/payment.html
{%extends 'Lot/base.html'%} {% load bootstrap3 %} {% load static %} {% block content %}
<br><br><br><br><br><br><br>
<div class="container">
  <form action="{% url 'lotOwner:Payment' current_profile.id %}" method="post" enctype="multipart/form-data">
    {%csrf_token%} {% bootstrap_form form %}
    <input type="submit" class="btn btn-warning btn-lg" value="Save Changes">
  </form>
</div>
{% endblock %}