driver/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'driver'

urlpatterns = [
    url(r'^search/', views.search_location, name='Search'),
    url(r'^edit-profile/', views.edit_profile, name='edit_profile'),
    url(r'^profile/(\d+)', views.update_profile, name='profile'),
    url(r'^car-details/', views.car_details, name='car_details'),
    url(r'^$', views.home, name='home'),
    url(r'^home/$', views.homed, name='homed'),
    url(r'^pay/$', views.trigger_payment, name='trigger_payment'),
    url(r'^status-success/$', views.status_success, name='status_success'),
    url(r'^status-failed/$', views.status_failed, name='status_failed'),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

egeshaProject/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from . import views as project_views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', project_views.landing, name='landing'),
    url(r'^lot/', include('lotOwner.urls')),
    url(r'^operator/', include('lotManager.urls')),
    url(r'^user/', include('accounts.urls')),
    url(r'^driver/', include('driver.urls')),
    # url(r'^egeshapay/', include('egeshapay.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

driver/models.py
from django.db import models
from accounts.models import DriverProfile
from lotOwner.models import LotDetails
import datetime as dt
from django.contrib.auth.models import User
# Create your models here.
class Cardetails(models.Model):
    '''
    class for populating details of the car
    '''
    car_plate = models.CharField(max_length = 30,default = 'KCA101Z',null = True)
    car_make = models.CharField(max_length = 30, default ='RangeRover', null = True)
    driver = models.ForeignKey(DriverProfile, null = True,on_delete=models.CASCADE)

class Timein(models.Model):
    '''
    class for populating timein details
    '''
    
    time_in = models.TimeField()
   
class Timeout(models.Model):
    '''
    class for populating timeout details
    '''
    
    time_out = models.TimeField()

driver/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Cardetails,Timein,Timeout
# from datetimewidget.widgets import DateTimeWidget

# cardetails form
class CardetailsForm(forms.ModelForm):
    class Meta:
        model = Cardetails
        fields = ['car_plate','car_make']

#timein form
class TimeinForm(forms.ModelForm):
    class Meta:
        model = Timein
        fields = ['time_in']
        dateTimeOptions = {
        'format': 'HH:ii P',
        'autoclose': True,
        'showMeridian' : True
        }
        widgets = {
         #NOT Use localization and set a default format
        # 'datetime': DateTimeWidget(options = dateTimeOptions)
        }
#timeout form
class TimeoutForm(forms.ModelForm):
    class Meta:
        model = Timeout
        fields = ['time_out']

        dateTimeOptions = {
        'format': 'HH:ii P',
        'autoclose': True,
        'showMeridian' : True
        }
        widgets = {
        #NOT Use localization and set a default format
        # 'datetime': DateTimeWidget(options = dateTimeOptions)
        }

driver/views.py
from .forms import CardetailsForm,TimeinForm,TimeoutForm
from django.shortcuts import render,redirect,get_object_or_404
from .models import Cardetails,Timein,Timeout
from django.http import Http404
from accounts.models import DriverProfile
from accounts.forms import EditDriver,EditUserForm
from lotOwner.models import Location
from django.core import serializers
from django.core.serializers import serialize
import json
from django.core.serializers.json import DjangoJSONEncoder
# Create your views here.
import africastalking

def homed(request):
    '''
    function to display driver and car details
    '''
    title="Egesha | Home "
    try:
        cardetails = Cardetails.objects.filter(id = request.user.id)
        profile = DriverProfile.objects.filter(id =request.user.id)
        user = request.user
    except ValueError:
        Http404

    return render(request,'user/indexed.html',{"cardetails":cardetails,"profile":profile,"user":user})

def car_details(request):
    '''
    function to populate the details of the car
    '''
    title="Egesha | Car Details "
    current_user = request.user
    cardetails = Cardetails.objects.filter(id = request.user.id)
    profile = DriverProfile.objects.filter(id =request.user.id)
    try:

        if request.method == 'POST':
            cardetails_form = CardetailsForm(request.POST, request.FILES)

            if cardetails_form.is_valid():
                cardetails = cardetails_form.save(commit=False)

                cardetails.user=current_user

                cardetails.save()

                return redirect('/driver/home/')

        else:
            cardetails_form = CardetailsForm

    except ValueError:
        Http404
    context = {
        "title": title,
        "cardetails_form": cardetails_form,
        "profile": profile,
        "cardetails": cardetails
        }
    return render(request, 'user/cardetails.html', context)


def edit_profile(request):
    '''
    function to populate the details of the profile
    '''
    title="Egesha | Profile Form "
    current_user = request.user
    try:
        if request.method == 'POST':

            driver_form  = EditDriver(request.POST,request.FILES)
            user_form = EditUserForm(request.POST, request.FILES)
            if driver_form.is_valid() and user_form.is_valid():

                driverdetails = driver_form.save(commit=False)
                userdetails = user_form.save(commit=False)

                driverdetails.user=current_user
                userdetails.user=current_user

                driverdetails.save()
                userdetails.save()
                return redirect('/driver/car-details')

        else:
            driver_form  = EditDriver()
            user_form = EditUserForm()

    except ValueError:
        Http404

    return render(request, 'user/profileform.html', {"title":title,"driver_form":driver_form,"user_form":user_form})

def update_profile(request,id):
    '''
    function to update profile
    '''
    title="Egesha | edit-profile "
    current_user = DriverProfile.objects.get(id = id)
    try:
        if request.method == 'POST':

            driver_form  = EditDriver(request.POST,request.FILES, instance = current_user)

            if driver_form.is_valid():
                driverdetails = driver_form.save(commit=False)
                driverdetails.user=current_user
                driverdetails.save()

                return redirect('/driver')

        else:
            driver_form  = EditDriver()
    except ValueError:
        Http404

    return render(request, 'user/editprofile.html', {"title":title,"driver_form":driver_form,"id":id,"current_user":current_user})

def home(request):
    '''
    function to display driver and car details
    '''
    title="Egesha | Home "
    try:
        cardetails = Cardetails.objects.filter(id = request.user.id)
        profile = DriverProfile.objects.filter(id =request.user.id)
        timein = Timein.objects.all()
        timeout = Timeout.objects.all()
        user = request.user
    except ValueError:
        Http404


    return render(request,'user/index.html',{"cardetails":cardetails,"profile":profile,"timeout":timeout,"timein":timein,"user":user})


def trigger_payment(request):
    africastalking.initialize(username='sandbox', api_key='4caafe95008a0a8ba2df43746a62238715dd1f3f3517be3a898402d40542c034')
    payment = africastalking.Payment
    res = payment.mobile_checkout(product_name='egesha',phone_number='+254720676920', currency_code='KES', amount=4000)
    return redirect('/driver/')

def search_location(request):
    current_user=request.user.id
    search_term=request.GET.get("location")
    spots=list(Location.search(search_term))



    print(spots)
    coords={"1":1,"2":2}
    coords_json=json.dumps(coords,cls=DjangoJSONEncoder)
    spots_json=serializers.serialize('json',spots,cls=DjangoJSONEncoder)
    searched_locations=Location.search(search_term)

    return render (request,'user/search.html',{"coords_json":coords_json,"spots_json":spots_json,"searched_locations":searched_locations})

def time(request):
    '''
    function to populate the time into the carlot
    '''
    title="Egesha | Time In "
    current_user = request.user
    try:
        if request.method == 'POST':
            timein_form = TimeinForm(request.POST, request.FILES)
            timeout_form = TimeoutForm(request.POST, request.FILES)
            if timein_form.is_valid() and timeout_form.is_valid():
                timein = timein_form.save(commit=False)
                timeout = timeout_form.save(commit=False)

                timein.user=current_user
                timeout.user=current_user

                timein.save()
                timeout.save()

                return redirect('/driver/')

        else:
            timein_form  = TimeinForm
            timeout_form  = TimeoutForm

    except ValueError:
        Http404

    return render(request, 'user/time.html', {"title":title,"timein_form": timein_form,"timeout_form": timeout_form})

def status_success(request):
    return render (request,'user/status_success.html')

def status_failed(request):
    return render (request,'user/status_failed.html')

driver/templates/user/cardetails.html
{%extends 'user/base.html'%} {% load bootstrap3 %} {% load static %}
<!--  -->
{% block content %} {{form.media}}
<br><br><br>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-4 col-md-3 sidebar well" style="background:white;">
            <br> {% if user %}
            <div class="">
                <!-- Heading -->
                <h2 class="text-center mb-4">
                    {{ user.username|title }}
                </h2>
            </div>{% endif %}
            <br> {% if profile %}{% for profile in profile %}
            <!-- Preheading -->
            <img src=" {{ profile.avatar.url }}" class="img-fluid img-responsive" alt="avatar">

            <!-- Heading -->
            <p class="text-center mb-4" data-animation="fadeUp" data-animation-order="1" data-animation-trigger="entered">
                {{ profile.bio}}
            </p>
            <p class="text-center mb-4" data-animation="fadeUp" data-animation-order="1" data-animation-trigger="entered">
                {{ profile.license}}
            </p>
            <p class="text-center mb-4" data-animation="fadeUp" data-animation-order="1" data-animation-trigger="entered">
                {{ profile.phone_number}}
            </p>
            {% endfor %} {% endif %} {% if cardetails %}{% for cardetails in cardetails %}
            <!-- Preheading -->
            <h1 class="text-black text-muted text-uppercase text-center text-sm" data-animation="fadeUp" data-animation-order="0" data-animation-trigger="entered">
                {{ cardetails.car_make }}
            </h1>

            <!-- Heading -->
            <h3 class="text-center mb-4" data-animation="fadeUp" data-animation-order="1" data-animation-trigger="entered">
                {{ cardetails.car_plate }}
            </h3>
            {% endfor %}{% endif %}

        </div>

    </div>

    <div class="col-sm-8 col-sm-offset-4 col-md-9 col-md-offset-3 main" style="background-color:#D5DFD5;">

        <div class="container-fluid"></div>
        <h1 class="page-header">Car details</h1>
        <br><br>
        <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-6 well">
                <!--  -->
                {{form.media}}
                <form action="{%url 'driver:car_details' %}" method="post" enctype="multipart/form-data">
                    {%csrf_token%} {% bootstrap_form cardetails_form%}
                    <input type="submit" class="btn btn-success btn-lg" value="Post">
                </form>
            </div>
            <div class="col-md-3"></div>
        </div>
    </div>
    <br><br><br><br><br><br><br><br><br><br>
</div>
</div>

</div>


<!--  -->
{%endblock%}

driver/templates/user/editprofile.html
{%extends 'user/base.html'%} {% load bootstrap3 %} {% load static %} {% block content %} {{form.media}}

<div class="container-fluid" style="padding-top: 6.5%; background-color:#D5DFD5;">
    <div class="row">
        <h1 class="text-center">
            <strong>Edit Profile</strong>
        </h1>
        <div class="col-md-3"></div>
        <div class="col-md-6 well">
            <!--  -->
            {{form.media}}
            <form action="{%url 'driver:profile' current_user.id %}" method="post" enctype="multipart/form-data">
                {%csrf_token%}{% bootstrap_form driver_form%}
                <input type="submit" class="btn btn-info btn-lg" value="Save">
            </form>
        </div>
        <div class="col-md-3"></div>
    </div>
    <br>
</div>

<!--  -->
{%endblock%}

driver/templates/user/index.html
{%extends 'user/base.html'%} {% load bootstrap3 %}{% load static%} {{block.super}}
<!--  -->
{% block content %}
<br><br><br>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-4 col-md-3 sidebar well" style="background:white;">
            <br> {% if user %}
            <div class="">
                <!-- Heading -->
                <h2 class="text-center mb-4">
                    Hello {{ user.username|title }}, Please search for a parking location..
                </h2>
            </div>{% endif %}
            <div class="row justify-content-center">
                <form class="navbar-form" role="search" action="{% url 'driver:Search' %}">
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="Enter location " name="location">
                        <div class="input-group-btn">
                            <button class="btn btn-default" type="submit">
                    <i class="glyphicon glyphicon-search"></i>
                </button>
                        </div>
                    </div>
                </form>

                <!-- </div> -->
            </div>
            <br> {% if profile %}{% for profile in profile %}
            <!-- Preheading -->
            <img src=" {{ profile.avatar.url }}" class="img-fluid img-responsive" alt="avatar">

            <!-- Heading -->
            <p class="text-center mb-4" data-animation="fadeUp" data-animation-order="1" data-animation-trigger="entered">
                {{ profile.bio}}
            </p>
            <p class="text-center mb-4" data-animation="fadeUp" data-animation-order="1" data-animation-trigger="entered">
                LICENCE: {{ profile.license}}
            </p>
            <p class="text-center mb-4" data-animation="fadeUp" data-animation-order="1" data-animation-trigger="entered">
                NUMBER: {{ profile.phone_number}}
            </p>
            {% endfor %} {% endif %} {% if cardetails %}{% for cardetails in cardetails %}
            <!-- Preheading -->
            <h1 class="text-black text-muted text-uppercase text-center text-sm" data-animation="fadeUp" data-animation-order="0" data-animation-trigger="entered">
                {{ cardetails.car_make }}
            </h1>

            <!-- Heading -->
            <h3 class="text-center mb-4" data-animation="fadeUp" data-animation-order="1" data-animation-trigger="entered">
                {{ cardetails.car_plate }}
            </h3>
            {% endfor %}{% endif %}

        </div>

    </div>
    <div class="col-sm-8 col-sm-offset-4 col-md-9 col-md-offset-3 main" style="background-color:#D5DFD5;">
        <br><br>
        <div class="container-fluid">
            <h1 class="page-header">Top Rated</h1>
            <!-- <h2 class="text-muted">free!</h2> -->

        </div>
        <br><br>
        <div class="container-fluid text-center">

            <div id="map" class="well"></div>

        </div>

    </div>
</div>
</div>

<script>
    function initMap() {
        var Nairobi = {
            lat: -1.2921,
            lng: 36.8219
        };
        var map = new google.maps.Map(document.getElementById('map'), {
            zoom: 14,
            center: Nairobi
        });
        var marker = new google.maps.Marker({
            position: Nairobi,
            map: map
        });
    }
</script>
<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCK_t72XTSivEU3POATANkgjcWilYv5UT4&callback=initMap "></script>


<!--  -->
{% endblock %}

driver/templates/user/indexed.html
{%extends 'user/base.html'%} {% load bootstrap3 %}{% load static%}

<!--  -->
{% block content %}
<br><br><br>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-4 col-md-3 sidebar well" style="background:white;">
            <br> {% if user %}
            <div class="">
                <!-- Heading -->
                <h2 class="text-center mb-4">
                    {{ user.username|title }}
                </h2>
            </div>{% endif %}
            <div class="row justify-content-center">
                <form class="navbar-form" role="search" action="{% url 'driver:Search' %}">
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="Enter location " name="location">
                        <div class="input-group-btn">
                            <button class="btn btn-default" type="submit">
              <i class="glyphicon glyphicon-search"></i>
            </button>
                        </div>
                    </div>
                </form>

                <!-- </div> -->
            </div>
            <br>{% if request.user.driver_profile %}
            <div class="pay">
                <br>
                <form class="" action="index.html" method="post">
                    <button type="submit" class="btn btn-lg btn-default btn-block text-center text-sm">
      <a href="https://rave.flutterwave.com/pay/payegesha" target="_blank">PAY NOW</a>

    </button>
                </form>



                <!--  -->
                {%else%}
                <button type="submit" class="btn btn-lg btn-default btn-block text-center text-sm">
    <a href="{% url 'driver:edit_profile'%}">BOOK NOW</a>
    <!-- <a href="https://rave.flutterwave.com/pay/egeshaqhk5" target="_blank">BOOK NOW</a> -->


    <!--  -->
 {%endif%}
<br>
<br>
 {% if profile %}{% for profile in profile %}
            <!-- Preheading -->
            <img src=" {{ profile.avatar.url }}" class="img-fluid img-responsive" alt="avatar">

            <!-- Heading -->
            <p class="text-center mb-4" data-animation="fadeUp" data-animation-order="1" data-animation-trigger="entered">
                {{ profile.bio}}
            </p>
            <p class="text-center mb-4" data-animation="fadeUp" data-animation-order="1" data-animation-trigger="entered">
                LICENCE: {{ profile.license}}
            </p>
            <p class="text-center mb-4" data-animation="fadeUp" data-animation-order="1" data-animation-trigger="entered">
                NUMBER: {{ profile.phone_number}}
            </p>
            {% endfor %} {% endif %} {% if cardetails %}{% for cardetails in cardetails %}
            <!-- Preheading -->
            <h1 class="text-black text-muted text-uppercase text-center text-sm" data-animation="fadeUp" data-animation-order="0" data-animation-trigger="entered">
                {{ cardetails.car_make }}
            </h1>

            <!-- Heading -->
            <h3 class="text-center mb-4" data-animation="fadeUp" data-animation-order="1" data-animation-trigger="entered">
                {{ cardetails.car_plate }}
            </h3>
            {% endfor %}{% endif %}
        </div>

    </div>

</div>
</div>
<div class="col-sm-8 col-sm-offset-4 col-md-9 col-md-offset-3 main" style="background-color:#D5DFD5;">
    <br><br>
    <div class="container-fluid">
        <h1 class="page-header">Top Rated</h1>
        <!-- <h2 class="text-muted">free!</h2> -->

    </div>
    <br><br>
    <div class="container-fluid text-center">

        <div id="map" class="well"></div>

    </div>

</div>
</div>
</div>

<script>
    function initMap() {
        var Nairobi = {
            lat: -1.2921,
            lng: 36.8219
        };
        var map = new google.maps.Map(document.getElementById('map'), {
            zoom: 14,
            center: Nairobi
        });
        var marker = new google.maps.Marker({
            position: Nairobi,
            map: map
        });
    }
</script>
<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCK_t72XTSivEU3POATANkgjcWilYv5UT4&callback=initMap"></script>


<!--  -->
{% endblock %}

driver/templates/user/navbar.html
{% load bootstrap3 %}
<!--  -->
{% load static%}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body data-spy="scroll" data-target=".navbar" data-offset="50">

  <nav class="navbar navbar-default navbar-fixed-top justify-content-between" style="height:75px; padding-top:10px; margin-bottom:0">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="/" style="padding-top:0px;">
          <img class="img-responsive img-fluid" src="{% static '/images/logo.png' %}" width="65px" height="65px" alt="icon"><span></span>
        </a>
        <a class="navbar-brand" href="/driver/" style="font-family: 'Lobster', cursive; font-weight: 700;font-size: 2.5em;"><strong>Egesha</strong></a>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">


        <ul class="nav navbar-nav">


        </ul>
        <ul class="nav navbar-nav navbar-right pull-right">
          <li>
            <a href="/user/logout" style="font-family: 'Raleway', sans-serif; color:black;font-size: 1.2em;">Logout</a>
          </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">

          <li class="dropdown">
            <a href="#" style="font-family: 'Raleway', sans-serif; color:black;font-size: 1.2em;" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><strong>{{user.username|title}} </strong><span class="caret"></span></a>
            <ul class="dropdown-menu">

              <li class="text-center text-muted" style="font-family: 'Raleway', sans-serif; color:black;font-size: 1.2em;"><strong>@ {{user.username}}</strong></li>
              <li role="separator" class="divider"></li>
              <li><a href="#" style="font-family: 'Raleway', sans-serif; color:black;font-size: 1.2em;">Edit Profile</a></li>
              <li><a href="{%url 'driver:car_details'%}" style="font-family: 'Raleway', sans-serif;font-size: 1.2em;color:black;">Add Car Details<span class="sr-only">(current)</span></a></li>

            </ul>
      </div>
    </div>
  </nav>
</body>

driver/templates/user/search.html
{%extends 'user/base.html'%} {% load bootstrap3 %}{% load static%} {% block content %}
<br><br><br>

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-4 col-md-3 sidebar " style="background:white;">
            <br> {% if user %}
            <div class="">
                <!-- Heading -->
                <h2 class="text-center mb-4">
                    {{ user.username|title }}
                </h2>
            </div>{% endif %}
            <br>

            <div class="row justify-content-center">
                <form class="navbar-form" role="search" action="{% url 'driver:Search' %}">
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="Enter location " name="location">
                        <div class="input-group-btn">
                            <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                        </div>
                    </div>
                </form>


            </div>

            {% if profile %} {% for profile in profile %}
            <div class="well" style="background-color:#D5DFD5;">
                <div class="container">
                    <div class="row justify-content-center align-items-center">

                        <div class="col-md-6 col-lg-7" style="padding-top: 15%;">

                            <!-- Preheading -->
                            <img src=" {{ profile.avatar.url }}" alt="avatar">

                            <!-- Heading -->
                            <p class="text-center mb-4" data-animation="fadeUp" data-animation-order="1" data-animation-trigger="entered">
                                {{ profile.bio}}
                            </p>
                            <p class="text-center mb-4" data-animation="fadeUp" data-animation-order="1" data-animation-trigger="entered">
                                {{ profile.license}}
                            </p>
                            <p class="text-center mb-4" data-animation="fadeUp" data-animation-order="1" data-animation-trigger="entered">
                                {{ profile.phone_number}}
                            </p>

                        </div>{% endfor %}{% endif %}

                        <br> {% if cardetails %}{% for cardetails in cardetails %}
                        <div class="col-md-6 col-lg-7" style="padding-top: 15%;">

                            <!-- Preheading -->
                            <h1 class="text-black text-muted text-uppercase text-center text-sm" data-animation="fadeUp" data-animation-order="0" data-animation-trigger="entered">
                                {{ cardetails.car_make }}
                            </h1>

                            <!-- Heading -->
                            <h3 class="text-center mb-4" data-animation="fadeUp" data-animation-order="1" data-animation-trigger="entered">
                                {{ cardetails.car_plate }}
                            </h3>


                        </div>
                        <!-- / .row -->
                    </div>
                </div>

            </div>
            {% endfor %}{% endif %} {% if request.user.driver_profile %}
            <div class="pay">
                <br>
                <form class="" action="index.html" method="post">
                    <button type="submit" class="btn btn-lg btn-default btn-block text-center text-sm">
      <a href="https://rave.flutterwave.com/pay/payegesha" target="_blank">PAY NOW</a>

    </button>
                </form>



                <!--  -->
                {%else%}
                <button type="submit" class="btn btn-lg btn-default btn-block text-center text-sm">
    <a href="{% url 'driver:edit_profile'%}">BOOK NOW</a>
    <!-- <a href="https://rave.flutterwave.com/pay/egeshaqhk5" target="_blank">BOOK NOW</a> -->


    <!--  -->
    {%endif%}
            </div>
</div>
<div class="col-sm-8 col-sm-offset-4 col-md-9 col-md-offset-3 main" style="background-color:#D5DFD5;">
                <br><br>

                <div class="container-fluid">
                    <h1 class="page-header">Results </h1> {% if searched_locations %}
                    <h2>Found {{ searched_locations|length }} results of the searched location </h2> {% else %}
                    <h2> Found 0 results </h2> {% endif %}

                </div>

  }
</script>
<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBmrKc7FjQwLm9vEtseo5LK7Z6M_1aPm5k&callback=initMap"></script>
<!--we load the api from the specified api, the async attribute allows the page to
    load as the api loads the call back paramater executes the initMap() function that specifies the latitude and longitude of where the map will
    be centered
  -->


                    <div id="map" class="well"></div>

                </div>
                <br><br><br><br><br><br>
            </div>
        </div>
    </div>
    {% endblock %}
    <!--  -->
    {% block scripts %}

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    {% bootstrap_javascript %}
    <script>
        // we declare the following as global variables
        var map;
        var marker;
        var infowindow;
        var messagewindow;
        var marker1;
        var $lat;
        var $lon;

        function initMap() {
            //location of Nairobi is stored in a varibale
            var myLatLng = {
                lat: -1.28333,
                lng: 36.81667
            };
            var mombasa = {
                lat: -1.3007,
                lng: 36.7849
            };
            map = new google.maps.Map(document.getElementById('map'), {
                center: myLatLng,
                zoom: 13
            });
            // the marker is positioned at Nairobi
            //the infowindow retrives the form element when clicking a marker
            marker1 = new google.maps.Marker({
                position: myLatLng,
                map: map,
            })



            //we assign a click listener  with the addListener that creates a marker when the user clicks the map





            // we create a variable called spots that store the spots that we passed from the view function
            var spots = JSON.parse('{{spots_json|safe}}');
            console.log(spots);
            for (var i = 0; i < spots.length; i++) {
                console.log('yess its working');
                //we store the lat and long in the variables
                var lat = parseFloat(spots[i].fields.latitude)
                var lng = parseFloat(spots[i].fields.longitude)
                var name = spots[i].fields.name_of_location
                    //Assign them positions lat being index 0
                coords = [lat, lng]
                    //we log them to the console to check if the function is working
                    //console.log(coords);
                console.log(name)
                var LatLng = new google.maps.LatLng(coords[0], coords[1]);
                var marker = new google.maps.Marker({
                    position: LatLng,
                    map: map
                });

            }


        }
    </script>
    <!--we load the api from the specified api, the async attribute allows the page to
  load as the api loads the call back paramater executes the initMap() function that specifies the latitude and longitude of where the map will
  be centered
-->
    <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBmrKc7FjQwLm9vEtseo5LK7Z6M_1aPm5k&callback=initMap"></script>


    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery.matchHeight/0.7.0/jquery.matchHeight-min.js"></script>

    {% endblock %}