driver/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'driver'

urlpatterns = [
    url(r'^search/', views.search_location, name='Search'),
    url(r'^edit-profile/', views.edit_profile, name='edit_profile'),
    url(r'^profile/(\d+)', views.update_profile, name='profile'),
    url(r'^car-details/', views.car_details, name='car_details'),
    url(r'^$', views.home, name='home'),
    url(r'^home/$', views.homed, name='homed'),
    url(r'^pay/$', views.trigger_payment, name='trigger_payment'),
    url(r'^status-success/$', views.status_success, name='status_success'),
    url(r'^status-failed/$', views.status_failed, name='status_failed'),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

egeshaProject/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from . import views as project_views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', project_views.landing, name='landing'),
    url(r'^lot/', include('lotOwner.urls')),
    url(r'^operator/', include('lotManager.urls')),
    url(r'^user/', include('accounts.urls')),
    url(r'^driver/', include('driver.urls')),
    # url(r'^egeshapay/', include('egeshapay.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lotManager/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from . import views

from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static


app_name = 'lotManager'

urlpatterns = [

    url(r'^$', views.operator, name='operator'),
    url(r'^checkin/$', views.checkin, name='checkin'),
    url(r'^checkout/$', views.checkout, name='checkout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lotOwner/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'lotOwner'

urlpatterns=[
    url(r'^owner/',views.home, name='Lot'),
    url(r'^details/(\d+)',views.Lotdetail,name='Details'),
    url(r'^map/(\d+)',views.map,name='Map'),
    url(r'^location/(\d+)',views.location,name='Location'),
    url(r'^edit/(\d+)',views.edit_profile,name='Edit'),
    url(r'^edit_lot/(\d+)',views.edit_lot,name='Edit_Lot'),
    url(r'^payment/(\d+)',views.payment,name="Payment"),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load bootstrap3 %}
<!--  -->
{% load static%}{% load staticfiles%}
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="shortcut icon" type="image/png" href="{% static '/images/logo.png' %}" />
  <!--  -->
  <title style="font-family: 'Lobster', cursive;">Egesha - Home</title>
  <!--  -->
  {% block styles %}
  <!--  -->
  {% bootstrap_css %}
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css?family=Lobster|Montserrat|Raleway|Cookie" rel="stylesheet">
  <!-- <link rel="stylesheet" href="{% static 'css/styles.css' %}"> -->
  <!--  -->
  {% endblock %}
</head>

<body>

  {% include "navbar.html" %}
  <!--  -->
  {% block content %}
  <div class="">

  </div>
  {%endblock%}
  <!-- FOOTER -->

  <footer class="container-fluid" style="background-color: #f5f5f5; width: 100%; height: 60px;padding-top: 20px;">
    <div>
      <p class="text-muted text-center" style="font-family: 'Lobster', cursive; ">&copy; 2018 Egesha</p>
    </div>
  </footer>
  <!-- end footer -->
  <!--  -->
  {% block scripts %}
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  {% bootstrap_javascript %}
  <script src="{% static 'js/scripts.js'%}" type="text/javascript"></script>

  <!--  -->
  {% endblock %}
</body>

</html>

templates/landing.html
{%extends 'base.html'%}{% load bootstrap3 %}{% load static%}
<!--  -->
{% block content %}
<div class="container-fluid jumbotron text-center" style="background-color:#90AD90; background-image: url('{%static '/images/parkedlot.jpg'%}');background-size: cover; margin-top:0;">
  <br>
  <br><br><br><br><br><br>
  <div class="well" style="opacity:0.8; width:650px; margin-left:350px;">

    <h2 class="text-center" style="text:solid;">Optimising your parking experience</h2>
    <p class="text-muted text-center">Car parking reservation system for booking car park spaces online.</p>
  </div>
  <br>
  <br><br><br><br><br><br>
</div>
<div class="container-fluid">
  <div data-spy="scroll" data-target=".nav" data-offset="50">
    <!-- BEGIN NAVBAR -->
    <div class="nav text-center">
      <a style="color:#90AD90;" href="#driver">Driver</a>
      <a style="color:#90AD90;" href="#lotOwner">/ Lot Owner</a>
      <a style="color:#90AD90;" href="#lotManager">/ Lot Operation</a>
    </div>
    <!-- END NAVBAR -->
  </div>

  <hr style="background-color:#90AD90;">
  <br>
  <div class="container" style="padding-left:50px;">
    <div class="row">
      <div class="col-md-4">
        <img class="img-fluid img-responsive" src="{%static '/images/audi.jpg'%}" width="300px" height="250px" alt="">
        <h3>Automotive & Navigation</h3>
        <p>
          Egesha Parking provides a complete solution for <br> drivers, enabling them to easily find, compare, <br> pay and navigate to the best parking spot.
        </p>
      </div>
      <div class="col-md-4">
        <img class="img-fluid img-responsive" src="{%static '/images/smartcities.jpg'%}" width="300px" height="250px" alt="">
        <h3>Smart Cities</h3>
        <p>
          Egesha Parking helps cities unlock the value of <br> Big Data to cut costs, improve efficiency, and <br> enhance the parking experience for drivers.
        </p>
      </div>
      <div class="col-md-4">
        <img class="img-fluid img-responsive" src="{%static '/images/business.jpg'%}" width="300px" height="250px" alt="">
        <h3>Businesses</h3>
        <p>
          Egesha Parking provides businesses, lot owners <br> and operators with tools to manage and measure <br> your parking assets while also providing a platform <br> to communicate parking information directly to <br>drivers.
        </p>
      </div>
    </div>
  </div>
  <br>
  <hr style="background-color:#90AD90;">
  <br>
</div>

<div class="container">
  <a class="anchor" name="driver"></a>
  <div class="row">
    <img style="float:left; width:500px; height:400px;" src="{%static '/images/streetparking.jpg'%}" alt="earn with egesha">
    <div class="well" style="background-color: #D5DFD5; opacity:0.8; width:670px; height:400px; margin-left:500px; ">
      <h1 class="text-center">Find Parking</h1>
      <p>
        It's no secret that parking is a major pain point for drivers but what's not as well-documented is the very real impact parking has on urban mobility. Uninformed drivers create more traffic, pollution and have a negative impact on cities when they search
        for parking.
      </p>
      {%if user.is_authenticated%}
      <a href="{%url 'driver:home'%}" class="btn btn-primary">Park Now</a>
      <!--  -->
      {%else%}
      <a href="{%url 'login'%}" class="btn btn-primary">Park Now</a>
      <!--  -->
      {%endif%}
    </div>
  </div>
</div>
<br>
<div class="container">
  <a class="anchor" name="lotOwner"></a>
  <div class="row">
    <img style="float:right; width:500px; height:400px;" src="{%static '/images/undergroundlot.jpg'%}" alt="earn with egesha">
    <div class="well" style="background-color: #D5DFD5; opacity:0.8; width:670px; height:400px; margin-right:500px; ">
      <h1 class="text-center"> Let your Lot</h1>
      <p>
        Egesha Parking provides businesses, lot owners and operators with tools to manage and measure your parking assets while also providing a platform to communicate parking information directly to drivers.
      </p>
      <!--  -->
      {%if user.is_authenticated%}
      <a href="{%url 'lotOwner:Lot' %}" class="btn btn-primary text-center">Lot Owner</a>
      <!--  -->
      {%else%}
      <a href="{%url 'login'%}" class="btn btn-primary">Lot Owner</a>
      <!--  -->
      {%endif%}
    </div>

  </div>
  <br>
  <div class="container">
    <a class="anchor" name="lotManager"></a>
    <div class="row">
      <img style="float:left; width:500px; height:400px;" src="{%static '/images/parked.jpg'%}" alt="earn with egesha">
      <div class="well" style="background-color: #D5DFD5; opacity:0.8; width:670px; height:400px; margin-left:500px; ">
        <h1 class="text-center">Manage your Lot</h1>
        <p>
          It's no secret that parking is a major pain point for drivers but what's not as well-documented is the very real impact parking has on urban mobility. Uninformed drivers create more traffic, pollution and have a negative impact on cities when they search
          for parking.
        </p>
        {%if user.is_authenticated%}
        <a href="{%url 'lotManager:operator'%}" class="btn btn-primary">Lot Operation</a>
        <!--  -->
        {%else%}
        <a href="{%url 'login'%}" class="btn btn-primary">Lot Operation</a>
        <!--  -->
        {%endif%}
      </div>
    </div>
  </div>
  <br>
  <!--  -->
  {%endblock%}
  <!--  -->

templates/navbar.html
{% load bootstrap3 %}
<!--  -->
{% load static%}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body>
  <div class="">
    <div class="">

      <nav class="navbar navbar-default navbar-static-top justify-content-between" style="height:75px; padding-top:10px; margin-bottom:0">
        <div class="container-fluid">
          <div class="navbar-header">
            <a class="navbar-brand" href="/" style="padding-top:0px;">
              <img class="img-responsive img-fluid" src="{% static '/images/logo.png' %}" width="65px" height="65px" alt="icon"><span></span>
            </a>
            <a class="navbar-brand" href="/" style="font-family: 'Lobster', cursive; font-weight: 700;font-size: 2.5em;"><strong>Egesha</strong></a>
          </div>

          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

            <div class=" ">
              {% if user.is_authenticated %}
              <ul class="nav navbar-nav">

                <!-- <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Driver<span class="caret"></span></a>
                  <ul class="dropdown-menu"> -->
                <li><a href="{%url 'driver:home'%}" style="font-family: 'Raleway', sans-serif; color:black;font-size: 1.2em;"><strong>Book Now</strong></a></li>
                <li><a href="{%url 'lotOwner:Lot'%}" style="font-family: 'Raleway', sans-serif; color:black;font-size: 1.2em;"><strong>Let Your Lot</strong></a></li>
                <li><a href="{%url 'lotManager:operator'%}" style="font-family: 'Raleway', sans-serif; color:black;font-size: 1.2em;"><strong>Lot Operation</strong></a></li>
              </ul>
              <!-- Adding a search form  -->
              <div class="navbar-right pull-right">
                <ul class="nav navbar-nav navbar-right pull-right">
                  <li>
                    <a href="/user/logout" style="font-family: 'Raleway', sans-serif; color:black;font-size: 1.2em; margin-right:15px">Logout</a>
                  </li>
                </ul>
                <!--
                <form class="navbar-form" role="search" action="#">

                  <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search" name="profile" aria-label="Search">
                    <div class="input-group-btn">
                      <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                    </div>
                  </div>

                </form> -->
              </div>
              <!-- search form end -->
              <ul class="nav navbar-nav navbar-right">

                <li class="dropdown">
                  <a href="#" style="font-family: 'Raleway', sans-serif; color:black;font-size: 1.2em;" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><strong>{{user.username|title}} </strong></a>

                </li>
              </ul>

              {% else %}
              <ul class="nav navbar-nav navbar-right ">
                <li><a href="/user/accounts/login" style="font-family: 'Raleway', sans-serif; color:black;font-size: 1.2em;">Sign in</a></li>
                <li><a href="/user/accounts/register" style="font-family: 'Raleway', sans-serif; color:black;font-size: 1.2em;">Sign up</a></li>
              </ul>


              {% endif %}


            </div>
          </div>
        </div>
      </nav>

    </div>
  </div>

</body>