driver/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'driver'

urlpatterns = [
    url(r'^search/', views.search_location, name='Search'),
    url(r'^edit-profile/', views.edit_profile, name='edit_profile'),
    url(r'^profile/(\d+)', views.update_profile, name='profile'),
    url(r'^car-details/', views.car_details, name='car_details'),
    url(r'^$', views.home, name='home'),
    url(r'^home/$', views.homed, name='homed'),
    url(r'^pay/$', views.trigger_payment, name='trigger_payment'),
    url(r'^status-success/$', views.status_success, name='status_success'),
    url(r'^status-failed/$', views.status_failed, name='status_failed'),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

egeshaProject/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from . import views as project_views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', project_views.landing, name='landing'),
    url(r'^lot/', include('lotOwner.urls')),
    url(r'^operator/', include('lotManager.urls')),
    url(r'^user/', include('accounts.urls')),
    url(r'^driver/', include('driver.urls')),
    # url(r'^egeshapay/', include('egeshapay.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lotManager/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from . import views

from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static


app_name = 'lotManager'

urlpatterns = [

    url(r'^$', views.operator, name='operator'),
    url(r'^checkin/$', views.checkin, name='checkin'),
    url(r'^checkout/$', views.checkout, name='checkout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lotManager/models.py
from django.db import models
from django.contrib.auth.models import User
from accounts.models import ManagerProfile
from accounts.models import DriverProfile


# Create your models here.


class Parked(models.Model):
    '''
    class for populating details of the car
    '''
    car_plate = models.CharField(max_length = 30,default = 'KCA101Z',null = True)
    

lotManager/forms.py
from django import forms
from .models import Parked

class Parkedcars(forms.ModelForm):
    class Meta:
        model = Parked
        fields = ['car_plate']

lotManager/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse,Http404,HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from driver.models import Cardetails
from .models import Parked
from .forms import Parkedcars

def operator(request):
    cardetails = Cardetails.objects.all()

  

    return render(request,'lotManager/index.html',{"cardetails":cardetails})

def checkin(request):
    if request.method == 'POST':
        form = Parkedcars(request.POST,request.FILES)
        if form.is_valid():
            parked = form.save(commit=False) 
            parked.save()
    else:
        form = Parkedcars()

    return render(request,'lotManager/in.html',{"form":form})

def checkout(request):
   

    return render(request,'lotManager/out.html')

lotManager/templates/lotManager/base.html
{% load bootstrap3 %}
<!--  -->
{% load static%}
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="shortcut icon" type="image/png" href="{% static '/images/logo.png' %}" />
  <!--  -->
  <title style="font-family: 'Lobster', cursive;">Egesha - Lot Operator</title>
  <!--  -->
  {% block styles %}
  <!--  -->
  {% bootstrap_css %}
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css?family=Lobster|Montserrat|Raleway|Cookie" rel="stylesheet">
  <!-- <link rel="stylesheet" href="{% static 'css/styles.css' %}"> -->
  <!--  -->
  {% endblock %}
</head>

<body>
  {% include "lotManager/navbar.html" %}
  <!--  -->
  {% block content %}
  <div class="">

  </div>
  {%endblock%}
  <!-- FOOTER -->

  <footer class="container-fluid" style="background-color: #f5f5f5; width: 100%; height: 60px;padding-top: 20px;">
    <div>
      <p class="text-muted text-center" style="font-family: 'Lobster', cursive; ">&copy; 2018 Egesha</p>
    </div>
  </footer>
  <!-- end footer -->
  <!--  -->
  {% block scripts %}
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  {% bootstrap_javascript %}
  <script src="{% static 'js/scripts.js'%}" type="text/javascript"></script>

  <!--  -->
  {% endblock %}
</body>

</html>

lotManager/templates/lotManager/in.html
{%extends 'lotManager/base.html'%}{% load bootstrap3 %}{% load static%}
<!--  -->
{% block content %}

<style>
.checks{
  padding-top: 10%;
}
</style>



<br><br><br><br><br><br><br>

<div class="container checks">
    

           <form  action="" method="post" enctype="multipart/form-data" class="form-inline">
             {%csrf_token%}
         
             {% bootstrap_form form%}
             <input type="submit" class="btn btn-success btn-lg btns" value="Check-In">
           </form>
 

      </div>





 <!-- bootstrap cdn js link -->
 <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
 <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
 <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
{%endblock%}

lotManager/templates/lotManager/index.html
{%extends 'lotManager/base.html'%}{% load bootstrap3 %}{% load static%}
<!--  -->
{% block content %}

<style>
.checks{
  padding-top: 10%;
}
.cls{
  text-align: centre;
  padding-left: 39%;
}
</style>



<br><br><br><br><br><br><br>

<div class=" cls">
  <h2>Booked Parking</h2>
</div>


<div class="container">


<div class="row">
  <div class="col-md-4"> <h3>Driver Name</h3></div>

  <div class="col-md-4"><h3>Car Make</h3></div>

  <div class="col-md-4"><h3>Car Plate</h3></div>
</div>

</div>








<div class="container">
  {% for cardetail in cardetails %}
   <div class="row">
       <div class="col-md-4">{{user.username }} </div>
       <div class="col-md-4">{{cardetail.car_make}}</div>
       <div class="col-md-4">{{cardetail.car_plate}}</div>
     </div>
   {% endfor %}
</div>




 <!-- bootstrap cdn js link -->
 <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
 <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
 <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
{%endblock%}

lotManager/templates/lotManager/navbar.html
{% load bootstrap3 %}
<!--  -->
{% load static%}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body data-spy="scroll" data-target=".navbar" data-offset="50">

  <nav class="navbar navbar-default navbar-fixed-top justify-content-between" style="height:75px; padding-top:10px; margin-bottom:0">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="/" style="padding-top:0px;">
          <img class="img-responsive img-fluid" src="{% static '/images/logo.png' %}" width="65px" height="65px" alt="icon"><span></span>
        </a>
        <a class="navbar-brand" href="/driver/" style="font-family: 'Lobster', cursive; font-weight: 700;font-size: 2.5em;"><strong>Egesha</strong></a>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">


        <ul class="nav navbar-nav">
          <li class="">
            <a href="{% url 'lotManager:operator' %}" style="font-family: 'Raleway', sans-serif;font-size: 1.2em;color:black;">Lot Operations
                            <span class="sr-only">(current)</span>
                        </a>
          </li>

          <li class="">
            <a href="{% url 'lotManager:checkin' %}" style="font-family: 'Raleway', sans-serif;font-size: 1.2em;color:black;">Check-In
                            
                        </a>
          </li>

          <li class="">
            <a href="{% url 'lotManager:checkout' %}" style="font-family: 'Raleway', sans-serif;font-size: 1.2em;color:black;">Check-Out
                            
                        </a>
          </li>

        </ul>
        <ul class="nav navbar-nav navbar-right pull-right">
          <li>
            <a href="/user/logout" style="font-family: 'Raleway', sans-serif; color:black;font-size: 1.2em;">Logout</a>
          </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">

          <li class="dropdown">
            <a href="#" style="font-family: 'Raleway', sans-serif; color:black;font-size: 1.2em;" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><strong>{{user.username|title}} </strong><span class="caret"></span></a>
            <ul class="dropdown-menu">

              <li class="text-center text-muted" style="font-family: 'Raleway', sans-serif; color:black;font-size: 1.2em;"><strong>@ {{user.username}}</strong></li>
              <li role="separator" class="divider"></li>
              <li><a href="#" style="font-family: 'Raleway', sans-serif; color:black;font-size: 1.2em;">Edit Profile</a></li>
              <!-- <li>
                <a href="{% url 'driver:edit_profile'%}" style="font-family: 'Raleway', sans-serif; color:black;font-size: 1.2em;">Your profile</a>
              </li> -->

              <!-- <li>
                <a href="#" style="font-family: 'Raleway', sans-serif; color:black;font-size: 1.2em;">Change Password</a>
              </li> -->
              <!-- <li role="separator" class="divider"></li> -->

            </ul>
      </div>
    </div>
  </nav>
</body>

lotManager/templates/lotManager/out.html
{%extends 'lotManager/base.html'%}{% load bootstrap3 %}{% load static%}
<!--  -->
{% block content %}

<style>
.checks{
  padding-top: 10%;
}
</style>



<br><br><br><br><br><br><br>

<h4>
    checkout
</h4>


 <!-- bootstrap cdn js link -->
 <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
 <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
 <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
{%endblock%}

lotManager/templates/lotManager/trys.html
View or Remove API Signature
Developers: Do not share your credential information with anyone. Store in a secure location with limited access.
For preconfigured shopping carts: Copy and paste the API username, password, and signature into your shopping cart configuration or administration screen.

For building custom shopping carts: Store the following credential information in a secure location with limited access.

Credential Signature
API Username
marymbugua.nm_api1.gmail.com
Hide
API Password
HKMWAKXBW55WGGRS
Hide
Signature
AGxQ9iMmRRl5rOtl5EEvHrk.x1P9AsBshsslGpvDviLVlPn-QE.2I1dr
Hide
Request Date 7 June 2018 at 12:34:59 AM GMT-7
RemoveDone



DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'egesha',
        'USER': 'nish',
        'PASSWORD': 'Nish',
            }
}

# Paypal SetUp
PAYPAL_TEST = True
PAYPAL_WPP_USER = "marymbugua.nm_api1.gmail.com"
PAYPAL_WPP_PASSWORD = "HKMWAKXBW55WGGRS"
PAYPAL_WPP_SIGNATURE = "AGxQ9iMmRRl5rOtl5EEvHrk.x1P9AsBshsslGpvDviLVlPn-QE.2I1dr"